import { Charada } from "../src/types/interfaces"

export const charadas: Charada[] = [
    { id: 1, dica: "Algo que faz parte da natureza ou característica própria de algo", qtd_letras: 8, resposta: "INERENTE" },
    { id: 2, dica: "Consideração ou valorização do outro", qtd_letras: 8, resposta: "RESPEITO" },
    { id: 3, dica: "Algo característico e diferente do comum", qtd_letras: 8, resposta: "PECULIAR" },
    { id: 4, dica: "Ato de ofender ou rebaixar alguém", qtd_letras: 8, resposta: "DENEGRIR" },
    { id: 5, dica: "Pessoa que pratica o extermínio de um povo", qtd_letras: 8, resposta: "GENOCIDA" },
    { id: 6, dica: "Concordância ou autorização formal", qtd_letras: 8, resposta: "ANUENCIA" },
    { id: 7, dica: "Princípio de justiça baseado em igualdade e respeito", qtd_letras: 8, resposta: "EQUIDADE" },
    { id: 8, dica: "Documento ou pedido oficialmente aceito", qtd_letras: 8, resposta: "DEFERIDO" },
    { id: 9, dica: "Alguém que age com cautela e sabedoria", qtd_letras: 8, resposta: "PRUDENTE" },
    { id: 10, dica: "Algo que está prestes a acontecer", qtd_letras: 8, resposta: "IMINENTE" },
    { id: 11, dica: "Aquilo que define a natureza básica de algo", qtd_letras: 8, resposta: "ESSENCIA" },
    { id: 12, dica: "Propagação mundial de uma doença", qtd_letras: 8, resposta: "PANDEMIA" },
    { id: 13, dica: "Grande tragédia ou infortúnio", qtd_letras: 8, resposta: "DESGRAÇA" },
    { id: 14, dica: "Pessoa que tem aversão ou ódio a mulheres", qtd_letras: 8, resposta: "MISÓGINO" },
    { id: 15, dica: "Ideia inicial que serve de base para um raciocínio", qtd_letras: 8, resposta: "PREMISSA" },
    { id: 16, dica: "Alguém ou algo muito importante ou destacado", qtd_letras: 8, resposta: "EMINENTE" },
    { id: 17, dica: "Que existe apenas como ideia, não concreto", qtd_letras: 8, resposta: "ABSTRATO" },
    { id: 18, dica: "Alguém ou algo que entra em espaço alheio sem permissão", qtd_letras: 8, resposta: "INVASIVO" },
    { id: 19, dica: "Pessoa que perdeu a capacidade de pensar criticamente", qtd_letras: 8, resposta: "ALIENADO" },
    { id: 20, dica: "Instrumento musical de teclas", qtd_letras: 8, resposta: "PIANISTA" },
    { id: 21, dica: "Objeto usado para iluminar", qtd_letras: 8, resposta: "LANTERNA" },
    { id: 22, dica: "Brinquedo do playground", qtd_letras: 8, resposta: "GANGORRA" },
    { id: 23, dica: "Local onde acontecem julgamentos", qtd_letras: 8, resposta: "TRIBUNAL" },
    { id: 24, dica: "Avião de grande porte", qtd_letras: 8, resposta: "AERONAVE" },
    { id: 25, dica: "Peixe usado em pratos japoneses", qtd_letras: 6, resposta: "SALMAO" },
    { id: 26, dica: "Objetos usados para medir o tempo", qtd_letras: 8, resposta: "RELOGIOS" },
    { id: 27, dica: "Animal de grande porte usado para carga no deserto", qtd_letras: 6, resposta: "CAMELO" },
    { id: 28, dica: "Fenômeno natural de luz no céu", qtd_letras: 6, resposta: "AURORA" },
    { id: 29, dica: "Pessoa que vende produtos", qtd_letras: 8, resposta: "VENDEDOR" },
    { id: 30, dica: "Aquele que não é civilizado", qtd_letras: 8, resposta: "SELVAGEM" },
    { id: 31, dica: "Comida feita de massa e molho", qtd_letras: 8, resposta: "MACARRAO" },
    { id: 32, dica: "Instrumento de cordas", qtd_letras: 6, resposta: "VIOLAO" },
    { id: 33, dica: "Grande mamífero marinho", qtd_letras: 6, resposta: "BALEIA" },
    { id: 34, dica: "Animal que produz lã", qtd_letras: 6, resposta: "OVELHA" },
    { id: 35, dica: "Fruta verde por fora e vermelha por dentro", qtd_letras: 8, resposta: "MELANCIA" },
    { id: 36, dica: "Inseto que produz mel", qtd_letras: 6, resposta: "ABELHA" },
    { id: 37, dica: "Meio de transporte rápido (pl.)", qtd_letras: 6, resposta: "AVIOES" },
    { id: 38, dica: "Local de estudo", qtd_letras: 6, resposta: "ESCOLA" },
    { id: 39, dica: "Fruto cítrico (pl.)", qtd_letras: 6, resposta: "LIMOES" },
    { id: 40, dica: "Pequena montanha", qtd_letras: 6, resposta: "COLINA" },
    { id: 41, dica: "Grande felino de manchas", qtd_letras: 4, resposta: "ONCA" },
    { id: 42, dica: "Animal do pântano", qtd_letras: 6, resposta: "JACARE" },
    { id: 43, dica: "Soar pelo espaço aberto", qtd_letras: 4, resposta: "ECOA" },
    { id: 44, dica: "Parte do corpo", qtd_letras: 6, resposta: "CABECA" },
    { id: 45, dica: "Animal felino doméstico", qtd_letras: 4, resposta: "GATO" },
    { id: 46, dica: "A parte inferior de um calçado", qtd_letras: 4, resposta: "SOLA" },
    { id: 47, dica: "Fruta pequena e roxa (pl.)", qtd_letras: 4, resposta: "UVAS" },
    { id: 48, dica: "Som do riso", qtd_letras: 4, resposta: "HAHA" },
    { id: 49, dica: "Lugar para dormir", qtd_letras: 4, resposta: "CAMA" },
    { id: 50, dica: "Peixe utilizado em sushi", qtd_letras: 4, resposta: "ATUM" },
    { id: 51, dica: "Estado sólido da água", qtd_letras: 4, resposta: "GELO" },
    { id: 52, dica: "Metal valioso", qtd_letras: 4, resposta: "OURO" },
    { id: 53, dica: "Pequena casa de animais selvagens", qtd_letras: 4, resposta: "TOCA" },
    { id: 54, dica: "Sentimento profundo de afeição", qtd_letras: 4, resposta: "AMOR" },
    { id: 55, dica: "Aquilo que realmente aconteceu", qtd_letras: 4, resposta: "FATO" },
    { id: 56, dica: "Tendência que influencia a percepção", qtd_letras: 4, resposta: "VIES" },
    { id: 57, dica: "Pronome usado para se dirigir à pessoa", qtd_letras: 4, resposta: "VOCE" },
    { id: 58, dica: "História lendária ou crença popular", qtd_letras: 4, resposta: "MITO" },
    { id: 59, dica: "Palavra usada para perguntar ou comparar", qtd_letras: 4, resposta: "COMO" },
    { id: 60, dica: "Desordem total ou confusão extrema", qtd_letras: 4, resposta: "CAOS" },
    { id: 61, dica: "Sem direção, ao acaso", qtd_letras: 4, resposta: "ESMO" },
    { id: 62, dica: "Força de vontade, coragem ou determinação", qtd_letras: 4, resposta: "BRIO" },
    { id: 63, dica: "Aquilo que se faz, ato ou realização", qtd_letras: 4, resposta: "AÇAO" },
    { id: 64, dica: "Expressão que significa 'veja' ou 'observe'", qtd_letras: 4, resposta: "VIDE" },
    { id: 65, dica: "Forte desejo por algo ou necessidade intensa", qtd_letras: 4, resposta: "SEDE" },
    { id: 66, dica: "Conectivo usado para introduzir explicação", qtd_letras: 4, resposta: "POIS" },
    { id: 67, dica: "Depois de determinado tempo ou evento", qtd_letras: 4, resposta: "APÓS" },
    { id: 68, dica: "Condição de estar vivo", qtd_letras: 4, resposta: "VIDA" },
    { id: 69, dica: "Lugar onde alguém mora", qtd_letras: 4, resposta: "CASA" },
    { id: 70, dica: "Sensação de apreensão ou temor", qtd_letras: 4, resposta: "MEDO" },
    { id: 71, dica: "História ou jornada cheia de desafios", qtd_letras: 4, resposta: "SAGA" },
    { id: 72, dica: "Encargo, responsabilidade ou peso", qtd_letras: 4, resposta: "ANUS" },
    { id: 73, dica: "Momento de maior intensidade ou ponto máximo", qtd_letras: 4, resposta: "AUGE" },
    { id: 74, dica: "Destino ou propósito inevitável", qtd_letras: 4, resposta: "SINA" },
    { id: 75, dica: "Pessoa do sexo feminino", qtd_letras: 6, resposta: "MULHER" },
    { id: 76, dica: "Sinal gráfico que indica tonicidade ou pronúncia", qtd_letras: 6, resposta: "ACENTO" },
    { id: 77, dica: "Procurar ou tentar encontrar algo", qtd_letras: 6, resposta: "BUSCAR" },
    { id: 78, dica: "Algo leve, sutil ou de natureza quase espiritual", qtd_letras: 6, resposta: "ETEREO" },
    { id: 79, dica: "Aquilo que está implícito, não dito", qtd_letras: 6, resposta: "TACITO" },
    { id: 80, dica: "Palavra usada para indicar tempo ou circunstância", qtd_letras: 6, resposta: "QUANDO" },
    { id: 81, dica: "Penalidade ou aprovação formal que gera efeito legal", qtd_letras: 6, resposta: "SANÇAO" },
    { id: 82, dica: "Problema grave, ferida social ou sofrimento prolongado", qtd_letras: 6, resposta: "MAZELA" },
    { id: 83, dica: "Garantia dada como segurança de pagamento", qtd_letras: 6, resposta: "PENHOR" },
    { id: 84, dica: "Pessoa educada, gentil e respeitosa", qtd_letras: 6, resposta: "CORTES" },
    { id: 85, dica: "Desejo excessivo de possuir algo", qtd_letras: 6, resposta: "COBIÇA" },
    { id: 86, dica: "Livre de obrigação, carga ou culpa", qtd_letras: 6, resposta: "ISENTO" },
    { id: 87, dica: "Pessoa séria, reservada e de poucas palavras", qtd_letras: 6, resposta: "SISUDO" },
    { id: 88, dica: "Livrar alguém de uma obrigação ou responsabilidade", qtd_letras: 6, resposta: "EXIMIR" },
    { id: 89, dica: "Grande desejo, ânsia intensa por algo", qtd_letras: 6, resposta: "AVIDEZ" },
    { id: 90, dica: "Sensação de satisfação ou contentamento", qtd_letras: 6, resposta: "PRAZER" },
    { id: 91, dica: "Algo que ocorre com constância e repetição", qtd_letras: 6, resposta: "SEMPRE" }
];