import { Charada } from "../src/types/interfaces"

export const charadas: Charada[] = [
    { id: 1, resposta: "ABELHA", qtd_letras: 6, dica: "Inseto conhecido por produzir mel e viver em colmeias." },
    { id: 2, resposta: "ABJURADO", qtd_letras: 8, dica: "Que foi oficialmente renunciado ou rejeitado de forma solene." },
    { id: 3, resposta: "ABOLIR", qtd_letras: 6, dica: "Cancelar ou extinguir algo de maneira formal e definitiva." },
    { id: 4, resposta: "ABSOLUTO", qtd_letras: 8, dica: "Aquilo que é completo, total e sem qualquer limitação." },
    { id: 5, resposta: "ABSTRATO", qtd_letras: 8, dica: "Que existe apenas no campo das ideias, sem forma material." },
    { id: 6, resposta: "ABULIÇÃO", qtd_letras: 8, dica: "Estado caracterizado pela perda ou enfraquecimento da vontade." },
    { id: 7, resposta: "AÇÃO", qtd_letras: 4, dica: "Tudo aquilo que é feito; ato ou realização concreta." },
    { id: 8, resposta: "ACENTO", qtd_letras: 6, dica: "Sinal gráfico usado para indicar pronúncia ou tonicidade." },
    { id: 9, resposta: "ACURACIA", qtd_letras: 8, dica: "Qualidade de algo que é preciso, exato e sem margem de erro." },
    { id: 10, resposta: "ADMOESTA", qtd_letras: 8, dica: "Repreensão feita com objetivo educativo ou moral." },
    { id: 11, resposta: "ADNÔMICA", qtd_letras: 8, dica: "Ramo da biologia dedicado ao estudo e análise do material genético." },
    { id: 12, resposta: "ADSTRITO", qtd_letras: 8, dica: "Que está preso, vinculado ou sujeito a regras específicas." },
    { id: 13, resposta: "AEROLITO", qtd_letras: 8, dica: "Tipo de meteorito formado principalmente por rochas silicáticas." },
    { id: 14, resposta: "AERONAVE", qtd_letras: 8, dica: "Veículo aéreo projetado para voar e transportar pessoas ou cargas." },
    { id: 15, resposta: "AFERENTE", qtd_letras: 8, dica: "Nervo responsável por conduzir estímulos ao sistema nervoso central." },
    { id: 16, resposta: "AFLUENTE", qtd_letras: 8, dica: "Curso de água que deságua em outro rio maior." },
    { id: 17, resposta: "ALIENADO", qtd_letras: 8, dica: "Pessoa que perdeu a capacidade de reflexão crítica ou consciência social." },
    { id: 18, resposta: "ALMA", qtd_letras: 4, dica: "Essência espiritual ou princípio vital associado ao ser humano." },
    { id: 19, resposta: "AMBIGUAS", qtd_letras: 8, dica: "Que permite mais de uma interpretação possível." },
    { id: 20, resposta: "AMOR", qtd_letras: 4, dica: "Sentimento intenso de afeição, cuidado e ligação emocional." },
    { id: 21, resposta: "ANABIOSE", qtd_letras: 8, dica: "Estado de dormência extrema adotado por organismos em condições adversas." },
    { id: 22, resposta: "ANALOGIA", qtd_letras: 8, dica: "Comparação entre coisas diferentes para facilitar compreensão ou explicação." },
    { id: 23, resposta: "ANFIBIOS", qtd_letras: 8, dica: "Classe de vertebrados que vive parte da vida na água e parte em terra." },
    { id: 24, resposta: "ANGELICO", qtd_letras: 8, dica: "Relativo a anjo; associado à pureza e ao celestial." },
    { id: 25, resposta: "ANUENCIA", qtd_letras: 8, dica: "Consentimento ou autorização concedida de forma oficial." },
    { id: 26, resposta: "APEX", qtd_letras: 4, dica: "Ponto mais elevado ou grau máximo atingido." },
    { id: 27, resposta: "APLAUSOS", qtd_letras: 8, dica: "Demonstração de aprovação por meio de palmas." },
    { id: 28, resposta: "APOCRIFO", qtd_letras: 8, dica: "Texto ou obra cuja autenticidade é questionada." },
    { id: 29, resposta: "APREÇO", qtd_letras: 6, dica: "Sentimento de consideração, estima ou valorização." },
    { id: 30, resposta: "ARBITRAR", qtd_letras: 8, dica: "Decidir ou julgar uma disputa com base em critério próprio." },
    { id: 31, resposta: "ARCADICO", qtd_letras: 8, dica: "Relacionado a uma vida simples, campestre e idealizada." },
    { id: 32, resposta: "ARDILOSO", qtd_letras: 8, dica: "Que age com astúcia e utiliza artifícios para enganar." },
    { id: 33, resposta: "ARROJADO", qtd_letras: 8, dica: "Que demonstra coragem, ousadia e iniciativa." },
    { id: 34, resposta: "ATUM", qtd_letras: 4, dica: "Peixe muito utilizado na culinária japonesa." },
    { id: 35, resposta: "AUGE", qtd_letras: 4, dica: "Momento de maior intensidade ou ponto culminante." },
    { id: 36, resposta: "AUGUSTAR", qtd_letras: 8, dica: "Tornar algo grandioso, majestoso ou digno de honra." },
    { id: 37, resposta: "AURORA", qtd_letras: 6, dica: "Fenômeno natural luminoso observado no céu." },
    { id: 38, resposta: "AVAL", qtd_letras: 4, dica: "Garantia ou assinatura que assegura o pagamento de uma dívida." },
    { id: 39, resposta: "AVERIGUE", qtd_letras: 8, dica: "Ato de investigar ou examinar algo com atenção." },
    { id: 40, resposta: "AVIDEZ", qtd_letras: 6, dica: "Desejo intenso e excessivo por algo." },
    { id: 41, resposta: "AVILTADO", qtd_letras: 8, dica: "Que foi moralmente rebaixado ou humilhado." },
    { id: 42, resposta: "AVIÕES", qtd_letras: 6, dica: "Meios de transporte que se deslocam pelo ar (plural)." },
    { id: 43, resposta: "BALEIA", qtd_letras: 6, dica: "Grande mamífero marinho conhecido por seu tamanho." },
    { id: 44, resposta: "BALUARTE", qtd_letras: 8, dica: "Estrutura defensiva ou símbolo de forte proteção." },
    { id: 45, resposta: "BELIGERO", qtd_letras: 8, dica: "Inclinado à guerra, ao confronto ou à hostilidade." },
    { id: 46, resposta: "BILOCADO", qtd_letras: 8, dica: "Que se encontra em dois lugares ao mesmo tempo." },
    { id: 47, resposta: "BIOCICLO", qtd_letras: 8, dica: "Ciclo natural da circulação da matéria nos ecossistemas." },
    { id: 48, resposta: "BIOETICA", qtd_letras: 8, dica: "Área que estuda questões éticas ligadas às ciências da vida." },
    { id: 49, resposta: "BIOFILIA", qtd_letras: 8, dica: "Afinidade natural do ser humano pela vida e pela natureza." },
    { id: 50, resposta: "BIOMASSA", qtd_letras: 8, dica: "Quantidade total de matéria orgânica viva em um ambiente." },
    { id: 51, resposta: "BIOMEDIA", qtd_letras: 8, dica: "Área científica que integra conhecimentos da biologia com a medicina." },
    { id: 52, resposta: "BIOSFERA", qtd_letras: 8, dica: "Conjunto de todos os ecossistemas da Terra onde a vida é possível." },
    { id: 53, resposta: "BLIZZARD", qtd_letras: 8, dica: "Tempestade intensa caracterizada por neve, vento forte e baixa visibilidade." },
    { id: 54, resposta: "BOGOTANO", qtd_letras: 8, dica: "Pessoa natural ou habitante da capital colombiana, Bogotá." },
    { id: 55, resposta: "BORBULHA", qtd_letras: 8, dica: "Pequena esfera de gás formada dentro de um líquido." },
    { id: 56, resposta: "BRIO", qtd_letras: 4, dica: "Força moral, coragem e energia para agir com firmeza." },
    { id: 57, resposta: "BUCO", qtd_letras: 4, dica: "Região do rosto situada entre o nariz e o lábio superior." },
    { id: 58, resposta: "BUCOLICO", qtd_letras: 8, dica: "Relacionado ao campo; simples, rural e ligado à vida pastoril." },
    { id: 59, resposta: "BUSCAR", qtd_letras: 6, dica: "Procurar algo com intenção, esforço ou persistência." },
    { id: 60, resposta: "CABECA", qtd_letras: 6, dica: "Parte superior do corpo humano onde ficam o cérebro e os sentidos." },
    { id: 61, resposta: "CACOFATO", qtd_letras: 8, dica: "Som desagradável gerado pela má combinação de palavras." },
    { id: 62, resposta: "CALCINEO", qtd_letras: 8, dica: "Relacionado ao calcanhar ou ao osso calcâneo do pé." },
    { id: 63, resposta: "CAMA", qtd_letras: 4, dica: "Móvel destinado ao descanso e ao sono." },
    { id: 64, resposta: "CAMELO", qtd_letras: 6, dica: "Animal adaptado ao deserto, usado para transporte e carga." },
    { id: 65, resposta: "CAOS", qtd_letras: 4, dica: "Estado de completa desordem, confusão ou falta de controle." },
    { id: 66, resposta: "CAPCIOSO", qtd_letras: 8, dica: "Enganoso; feito para confundir ou induzir ao erro." },
    { id: 67, resposta: "CARRASCO", qtd_letras: 8, dica: "Executor de punições severas; algoz." },
    { id: 68, resposta: "CASA", qtd_letras: 4, dica: "Local destinado à moradia de pessoas ou famílias." },
    { id: 69, resposta: "CASMURRO", qtd_letras: 8, dica: "Teimoso; que insiste em ideias sem aceitar mudanças." },
    { id: 70, resposta: "CATALISE", qtd_letras: 8, dica: "Processo químico que acelera reações sem ser consumido." },
    { id: 71, resposta: "CATOLICO", qtd_letras: 8, dica: "Universal; relativo à Igreja Católica." },
    { id: 72, resposta: "CAUTELAR", qtd_letras: 8, dica: "Preventivo; feito como medida de precaução." },
    { id: 73, resposta: "CAVILOSO", qtd_letras: 8, dica: "Malicioso; que age com astúcia ou intenção oculta." },
    { id: 74, resposta: "CEFALEIA", qtd_letras: 8, dica: "Termo médico utilizado para dor de cabeça." },
    { id: 75, resposta: "CESSANTE", qtd_letras: 8, dica: "Que deixa de existir; que se encerra ou termina." },
    { id: 76, resposta: "CHISTOSO", qtd_letras: 8, dica: "Engraçado; espirituoso e bem-humorado." },
    { id: 77, resposta: "CINTILHO", qtd_letras: 8, dica: "Pequeno brilho intermitente; centelha." },
    { id: 78, resposta: "CLAMORAR", qtd_letras: 8, dica: "Pedir ou gritar com intensidade e desespero." },
    { id: 79, resposta: "CLASSICO", qtd_letras: 8, dica: "Modelo tradicional que serve de referência." },
    { id: 80, resposta: "CLERICAL", qtd_letras: 8, dica: "Relacionado ao clero ou às atividades religiosas." },
    { id: 81, resposta: "COALIZAO", qtd_letras: 8, dica: "União de forças, grupos ou partidos com um objetivo comum." },
    { id: 82, resposta: "COBICA", qtd_letras: 6, dica: "Desejo exagerado de possuir algo, geralmente material." },
    { id: 83, resposta: "COERENTE", qtd_letras: 8, dica: "Lógico; que mantém consistência entre ideias ou ações." },
    { id: 84, resposta: "COLINA", qtd_letras: 6, dica: "Elevação do terreno menor que uma montanha." },
    { id: 85, resposta: "COLOQUIO", qtd_letras: 8, dica: "Conversa formal, debate ou conferência acadêmica." },
    { id: 86, resposta: "COMO", qtd_letras: 4, dica: "Palavra usada para perguntar, comparar ou explicar." },
    { id: 87, resposta: "COMPLEXA", qtd_letras: 8, dica: "Formada por muitas partes interligadas; intrincada." },
    { id: 88, resposta: "COMPLEXO", qtd_letras: 8, dica: "Difícil de entender; conjunto de elementos relacionados." },
    { id: 89, resposta: "CONCILIO", qtd_letras: 8, dica: "Reunião formal de autoridades religiosas para decisões." },
    { id: 90, resposta: "CONDIGNO", qtd_letras: 8, dica: "Digno; merecedor de recompensa ou punição." },
    { id: 91, resposta: "CONFLUIR", qtd_letras: 8, dica: "Encontrar-se ou juntar-se, como rios ou ideias." },
    { id: 92, resposta: "CONJECTO", qtd_letras: 8, dica: "Suposição baseada em indícios, não em certezas." },
    { id: 93, resposta: "CONTIGUO", qtd_letras: 8, dica: "Muito próximo; que está ao lado de outro." },
    { id: 94, resposta: "CONVEM", qtd_letras: 6, dica: "Ser adequado, oportuno ou apropriado." },
    { id: 95, resposta: "CORTES", qtd_letras: 6, dica: "Educado; gentil no trato com outras pessoas." },
    { id: 96, resposta: "CRITERIO", qtd_letras: 8, dica: "Regra ou padrão usado para avaliar algo." },
    { id: 97, resposta: "CROMOSSO", qtd_letras: 8, dica: "Estrutura celular que carrega informações genéticas." },
    { id: 98, resposta: "CUMPLICE", qtd_letras: 8, dica: "Pessoa que participa ou auxilia em um ato ilícito." },
    { id: 99, resposta: "DEFERIDO", qtd_letras: 8, dica: "Pedido ou solicitação oficialmente aceita." },
    { id: 100, resposta: "DENEGRIR", qtd_letras: 8, dica: "Difamar; manchar a reputação de alguém." },
    { id: 101, resposta: "DEPRECAR", qtd_letras: 8, dica: "Pedir algo com insistência; suplicar ou rogar." },
    { id: 102, resposta: "DESGRACA", qtd_letras: 8, dica: "Grande tragédia, infortúnio ou acontecimento negativo." },
    { id: 103, resposta: "DESTREZA", qtd_letras: 8, dica: "Habilidade adquirida por prática, precisão e controle." },
    { id: 104, resposta: "DILEMA", qtd_letras: 6, dica: "Situação difícil que exige escolher entre duas opções ruins." },
    { id: 105, resposta: "DISSIDIO", qtd_letras: 8, dica: "Conflito interno causado por divergências profundas." },
    { id: 106, resposta: "DOTE", qtd_letras: 4, dica: "Talento ou qualidade natural de uma pessoa." },
    { id: 107, resposta: "ECOA", qtd_letras: 4, dica: "Soar repetidamente em um espaço aberto." },
    { id: 108, resposta: "ELIDIR", qtd_letras: 6, dica: "Eliminar ou suprimir letras, sílabas ou ideias." },
    { id: 109, resposta: "EMINENTE", qtd_letras: 8, dica: "Superior ou notável; que se destaca dos demais." },
    { id: 110, resposta: "EMPIRICO", qtd_letras: 8, dica: "Baseado na experiência prática, não apenas na teoria." },
    { id: 111, resposta: "ENIGMICO", qtd_letras: 8, dica: "Misterioso; difícil de compreender ou decifrar." },
    { id: 112, resposta: "ENLEVADO", qtd_letras: 8, dica: "Tomado por encanto, admiração ou êxtase." },
    { id: 113, resposta: "ENLEVO", qtd_letras: 6, dica: "Estado de encantamento ou arrebatamento emocional." },
    { id: 114, resposta: "ENTE", qtd_letras: 4, dica: "Qualquer ser que existe ou pode existir." },
    { id: 115, resposta: "EQUIDADE", qtd_letras: 8, dica: "Princípio de justiça baseado na igualdade e no equilíbrio." },
    { id: 116, resposta: "ERMO", qtd_letras: 4, dica: "Lugar isolado, solitário e pouco frequentado." },
    { id: 117, resposta: "ESCOLA", qtd_letras: 6, dica: "Instituição destinada ao ensino e aprendizado." },
    { id: 118, resposta: "ESMO", qtd_letras: 4, dica: "Sem direção definida; ao acaso." },
    { id: 119, resposta: "ESSENCIA", qtd_letras: 8, dica: "Aquilo que define a natureza fundamental de algo." },
    { id: 120, resposta: "ESTEREIS", qtd_letras: 8, dica: "Incapaz de gerar frutos, resultados ou descendentes." },
    { id: 121, resposta: "ETEREO", qtd_letras: 6, dica: "Leve, sutil, quase espiritual ou intangível." },
    { id: 122, resposta: "EXIGUO", qtd_letras: 6, dica: "Muito pequeno em quantidade, tamanho ou duração." },
    { id: 123, resposta: "EXIMIO", qtd_letras: 6, dica: "Excelente; que se destaca pela perfeição." },
    { id: 124, resposta: "EXIMIR", qtd_letras: 6, dica: "Livrar alguém de uma obrigação ou dever." },
    { id: 125, resposta: "EXPURGAR", qtd_letras: 8, dica: "Eliminar impurezas; remover ou censurar conteúdos." },
    { id: 126, resposta: "FACTIVEL", qtd_letras: 8, dica: "Que pode ser realizado; possível de executar." },
    { id: 127, resposta: "FADO", qtd_letras: 4, dica: "Destino considerado inevitável ou pré-determinado." },
    { id: 128, resposta: "FASTIDIO", qtd_letras: 8, dica: "Sensação intensa de tédio, cansaço ou repulsa." },
    { id: 129, resposta: "FATO", qtd_letras: 4, dica: "Aquilo que realmente aconteceu; realidade." },
    { id: 130, resposta: "FICTICIO", qtd_letras: 8, dica: "Inventado; que não corresponde à realidade." },
    { id: 131, resposta: "FIEL", qtd_letras: 4, dica: "Leal; que demonstra constância e compromisso." },
    { id: 132, resposta: "FORTUITO", qtd_letras: 8, dica: "Que ocorre por acaso, sem intenção." },
    { id: 133, resposta: "FRENESIM", qtd_letras: 8, dica: "Estado de excitação extrema ou descontrole emocional." },
    { id: 134, resposta: "FRUGAL", qtd_letras: 6, dica: "Simples e moderado, especialmente na alimentação." },
    { id: 135, resposta: "GANGORRA", qtd_letras: 8, dica: "Brinquedo infantil que sobe e desce alternadamente." },
    { id: 136, resposta: "GATO", qtd_letras: 4, dica: "Animal doméstico felino conhecido por agilidade." },
    { id: 137, resposta: "GELIDO", qtd_letras: 6, dica: "Extremamente frio; de temperatura muito baixa." },
    { id: 138, resposta: "GELO", qtd_letras: 4, dica: "Estado sólido da água." },
    { id: 139, resposta: "GENOCIDA", qtd_letras: 8, dica: "Responsável pelo extermínio deliberado de um povo." },
    { id: 140, resposta: "GENOMICA", qtd_letras: 8, dica: "Ciência que estuda o conjunto completo de genes." },
    { id: 141, resposta: "HAHA", qtd_letras: 4, dica: "Expressão escrita do som do riso." },
    { id: 142, resposta: "HEDIONDO", qtd_letras: 8, dica: "Extremamente feio, repugnante ou horrível." },
    { id: 143, resposta: "HOLOFOTE", qtd_letras: 8, dica: "Luz potente usada para iluminar ou destacar algo." },
    { id: 144, resposta: "IDOLATRA", qtd_letras: 8, dica: "Quem admira ou venera algo de forma excessiva." },
    { id: 145, resposta: "IDONEO", qtd_letras: 6, dica: "Confiável e adequado para determinada função." },
    { id: 146, resposta: "IGNAVULO", qtd_letras: 8, dica: "Covarde; que demonstra falta de coragem." },
    { id: 147, resposta: "IMANENTE", qtd_letras: 8, dica: "Que existe ou atua de dentro; inerente." },
    { id: 148, resposta: "IMINENTE", qtd_letras: 8, dica: "Prestes a acontecer; muito próximo no tempo." },
    { id: 149, resposta: "IMPAVIDO", qtd_letras: 8, dica: "Que não demonstra medo diante do perigo." },
    { id: 150, resposta: "IMPAVIDO", qtd_letras: 8, dica: "Destemido; que não demonstra medo diante do perigo." },
    { id: 151, resposta: "INDIGENA", qtd_letras: 8, dica: "Originário de uma região; nativo de determinado local." },
    { id: 152, resposta: "INDOLE", qtd_letras: 6, dica: "Caráter ou temperamento natural de uma pessoa." },
    { id: 153, resposta: "INERENTE", qtd_letras: 8, dica: "Que faz parte da essência ou natureza de algo." },
    { id: 154, resposta: "INOCUO", qtd_letras: 6, dica: "Que não causa dano, prejuízo ou efeito negativo." },
    { id: 155, resposta: "INSULADO", qtd_letras: 8, dica: "Isolado física, social ou culturalmente." },
    { id: 156, resposta: "INVASIVO", qtd_letras: 8, dica: "Que invade espaços ou limites sem permissão." },
    { id: 157, resposta: "INVULGAR", qtd_letras: 8, dica: "Raro, incomum; fora do padrão habitual." },
    { id: 158, resposta: "ISENTO", qtd_letras: 6, dica: "Livre de obrigação, culpa ou responsabilidade." },
    { id: 159, resposta: "JACARE", qtd_letras: 6, dica: "Réptil de regiões alagadas e pântanos." },
    { id: 160, resposta: "JUBILOSO", qtd_letras: 8, dica: "Tomado por alegria intensa e entusiasmo." },
    { id: 161, resposta: "LACO", qtd_letras: 4, dica: "Vínculo afetivo ou relação de união." },
    { id: 162, resposta: "LANTERNA", qtd_letras: 8, dica: "Objeto portátil usado para iluminar ambientes escuros." },
    { id: 163, resposta: "LIMOES", qtd_letras: 6, dica: "Frutos cítricos de sabor ácido." },
    { id: 164, resposta: "LUCIDO", qtd_letras: 6, dica: "Que possui clareza mental e raciocínio consciente." },
    { id: 165, resposta: "LUDIBRIO", qtd_letras: 8, dica: "Engano intencional ou zombaria disfarçada." },
    { id: 166, resposta: "MACARRAO", qtd_letras: 8, dica: "Alimento feito de massa, comum na culinária italiana." },
    { id: 167, resposta: "MACROBIO", qtd_letras: 8, dica: "Organismo visível a olho nu, não microscópico." },
    { id: 168, resposta: "MAGNUM", qtd_letras: 6, dica: "Algo grande, importante ou de grande impacto." },
    { id: 169, resposta: "MAZELA", qtd_letras: 6, dica: "Problema grave, sofrimento persistente ou ferida social." },
    { id: 170, resposta: "MEDO", qtd_letras: 4, dica: "Sensação de apreensão diante de perigo real ou imaginário." },
    { id: 171, resposta: "MELANCIA", qtd_letras: 8, dica: "Fruta grande, verde por fora e vermelha por dentro." },
    { id: 172, resposta: "MICROBIO", qtd_letras: 8, dica: "Ser vivo microscópico, invisível sem instrumentos." },
    { id: 173, resposta: "MISOGINO", qtd_letras: 8, dica: "Pessoa que manifesta aversão ou ódio às mulheres." },
    { id: 174, resposta: "MITO", qtd_letras: 4, dica: "Narrativa lendária usada para explicar crenças ou origens." },
    { id: 175, resposta: "MULHER", qtd_letras: 6, dica: "Pessoa do sexo feminino." },
    { id: 176, resposta: "NEURONIO", qtd_letras: 8, dica: "Célula responsável pela transmissão de impulsos nervosos." },
    { id: 177, resposta: "NEVO", qtd_letras: 4, dica: "Neblina leve que reduz parcialmente a visibilidade." },
    { id: 178, resposta: "NEXO", qtd_letras: 4, dica: "Ligação lógica entre fatos, ideias ou argumentos." },
    { id: 179, resposta: "NITIDO", qtd_letras: 6, dica: "Claro, preciso e fácil de perceber." },
    { id: 180, resposta: "OMISSO", qtd_letras: 6, dica: "Que deixa de cumprir um dever ou obrigação." },
    { id: 181, resposta: "ONCA", qtd_letras: 4, dica: "Grande felino selvagem de pelagem manchada." },
    { id: 182, resposta: "ONUS", qtd_letras: 4, dica: "Encargo, peso ou responsabilidade assumida." },
    { id: 183, resposta: "OPRESSOR", qtd_letras: 8, dica: "Quem subjuga outros por força, abuso ou autoridade." },
    { id: 184, resposta: "OPUSCULO", qtd_letras: 8, dica: "Obra literária curta, geralmente crítica ou ensaística." },
    { id: 185, resposta: "OSMOTICA", qtd_letras: 8, dica: "Relativa ao processo físico-químico da osmose." },
    { id: 186, resposta: "OURO", qtd_letras: 4, dica: "Metal precioso de alto valor econômico." },
    { id: 187, resposta: "OVELHA", qtd_letras: 6, dica: "Animal domesticado conhecido pela produção de lã." },
    { id: 188, resposta: "PANDEMIA", qtd_letras: 8, dica: "Disseminação global de uma doença infecciosa." },
    { id: 189, resposta: "PARADOXA", qtd_letras: 8, dica: "Afirmação que contradiz a lógica comum." },
    { id: 190, resposta: "PECULIAR", qtd_letras: 8, dica: "Característico; diferente do que é comum." },
    { id: 191, resposta: "PENHOR", qtd_letras: 6, dica: "Garantia dada como segurança de uma dívida." },
    { id: 192, resposta: "PERVERSO", qtd_letras: 8, dica: "Inclinado à maldade, crueldade ou corrupção moral." },
    { id: 193, resposta: "PIANISTA", qtd_letras: 8, dica: "Músico especializado no instrumento piano." },
    { id: 194, resposta: "PIROLISE", qtd_letras: 8, dica: "Decomposição química causada pela ação do calor." },
    { id: 195, resposta: "POIS", qtd_letras: 4, dica: "Conectivo usado para introduzir explicação ou causa." },
    { id: 196, resposta: "PRAZER", qtd_letras: 6, dica: "Sensação de satisfação, alegria ou contentamento." },
    { id: 197, resposta: "PREMISSA", qtd_letras: 8, dica: "Ideia inicial que serve de base para um raciocínio." },
    { id: 198, resposta: "PROTIDEO", qtd_letras: 8, dica: "Relativo a proteínas e compostos proteicos." },
    { id: 199, resposta: "PRUDENTE", qtd_letras: 8, dica: "Pessoa que age com cautela, bom senso e sabedoria." },
    { id: 200, resposta: "QUANDO", qtd_letras: 6, dica: "Palavra usada para indicar tempo ou circunstância." },
    { id: 201, resposta: "RARO", qtd_letras: 4, dica: "Algo pouco comum ou difícil de encontrar." },
    { id: 202, resposta: "RELOGIOS", qtd_letras: 8, dica: "Objetos utilizados para medir e indicar o tempo." },
    { id: 203, resposta: "RESOLUTO", qtd_letras: 8, dica: "Que age com firmeza, decisão e determinação." },
    { id: 204, resposta: "RESPEITO", qtd_letras: 8, dica: "Consideração, apreço ou valorização do outro." },
    { id: 205, resposta: "RITO", qtd_letras: 4, dica: "Conjunto de práticas simbólicas ou cerimoniais." },
    { id: 206, resposta: "SAGA", qtd_letras: 4, dica: "Narrativa ou jornada marcada por desafios." },
    { id: 207, resposta: "SALMAO", qtd_letras: 6, dica: "Peixe muito usado na culinária japonesa." },
    { id: 208, resposta: "SANCAO", qtd_letras: 6, dica: "Penalidade ou aprovação formal com efeito legal." },
    { id: 209, resposta: "SEDE", qtd_letras: 4, dica: "Desejo intenso ou necessidade profunda." },
    { id: 210, resposta: "SELVAGEM", qtd_letras: 8, dica: "Que não é civilizado ou vive em estado natural." },
    { id: 211, resposta: "SEMPRE", qtd_letras: 6, dica: "Algo que ocorre de forma constante." },
    { id: 212, resposta: "SIMBIOSE", qtd_letras: 8, dica: "Relação próxima e benéfica entre seres diferentes." },
    { id: 213, resposta: "SINA", qtd_letras: 4, dica: "Destino considerado inevitável." },
    { id: 214, resposta: "SINDICAR", qtd_letras: 8, dica: "Investigar, examinar ou apurar detalhadamente." },
    { id: 215, resposta: "SISO", qtd_letras: 4, dica: "Capacidade de agir com prudência e juízo." },
    { id: 216, resposta: "SISUDO", qtd_letras: 6, dica: "Pessoa séria, reservada e de poucas palavras." },
    { id: 217, resposta: "SOBRIO", qtd_letras: 6, dica: "Que age com moderação, equilíbrio e lucidez." },
    { id: 218, resposta: "SOLA", qtd_letras: 4, dica: "Parte inferior de um calçado." },
    { id: 219, resposta: "SOLENE", qtd_letras: 6, dica: "Que inspira respeito por sua formalidade." },
    { id: 220, resposta: "SUBJUGAR", qtd_letras: 8, dica: "Dominar ou controlar alguém pela força." },
    { id: 221, resposta: "SUBMISSO", qtd_letras: 8, dica: "Que se sujeita passivamente à vontade alheia." },
    { id: 222, resposta: "SUTILEZA", qtd_letras: 8, dica: "Habilidade de perceber detalhes finos ou implícitos." },
    { id: 223, resposta: "TACITO", qtd_letras: 6, dica: "Que não é dito explicitamente, mas é entendido." },
    { id: 224, resposta: "TANGIVEL", qtd_letras: 8, dica: "Que pode ser tocado ou claramente percebido." },
    { id: 225, resposta: "TECITURA", qtd_letras: 8, dica: "Estrutura ou composição de algo." },
    { id: 226, resposta: "TECNECIO", qtd_letras: 8, dica: "Elemento químico artificial da tabela periódica." },
    { id: 227, resposta: "TEMA", qtd_letras: 4, dica: "Assunto central de uma obra ou discussão." },
    { id: 228, resposta: "TINO", qtd_letras: 4, dica: "Bom senso aplicado às decisões do cotidiano." },
    { id: 229, resposta: "TOCA", qtd_letras: 4, dica: "Abrigo ou casa de animais selvagens." },
    { id: 230, resposta: "TRIBUNAL", qtd_letras: 8, dica: "Local onde ocorrem julgamentos." },
    { id: 231, resposta: "UBIQUO", qtd_letras: 6, dica: "Que parece estar presente em toda parte." },
    { id: 232, resposta: "USUR", qtd_letras: 4, dica: "Apropriação indevida do que pertence a outro." },
    { id: 233, resposta: "UVAS", qtd_letras: 4, dica: "Frutas pequenas usadas na produção de vinho." },
    { id: 234, resposta: "VAGO", qtd_letras: 4, dica: "Indefinido, impreciso ou pouco claro." },
    { id: 235, resposta: "VENDEDOR", qtd_letras: 8, dica: "Pessoa que comercializa produtos ou serviços." },
    { id: 236, resposta: "VETO", qtd_letras: 4, dica: "Ato formal de proibir ou barrar uma decisão." },
    { id: 237, resposta: "VIDA", qtd_letras: 4, dica: "Condição de existir como ser vivo." },
    { id: 238, resposta: "VIDE", qtd_letras: 4, dica: "Expressão usada para indicar consulta ou observação." },
    { id: 239, resposta: "VIES", qtd_letras: 4, dica: "Tendência que influencia julgamento ou percepção." },
    { id: 240, resposta: "VIGOROSO", qtd_letras: 8, dica: "Que demonstra força, energia e vitalidade." },
    { id: 241, resposta: "VIOLAO", qtd_letras: 6, dica: "Instrumento musical de cordas." },
    { id: 242, resposta: "VOCE", qtd_letras: 4, dica: "Pronome usado para se dirigir a alguém." },
    { id: 243, resposta: "ZELO", qtd_letras: 4, dica: "Cuidado atento e dedicação no cumprimento de deveres." },
    { id: 244, resposta: "ZOOFITOS", qtd_letras: 8, dica: "Termo antigo para seres com aparência vegetal e animal." }
];